### ISSUE TITLE
Fresh Start

### ISSUE THREAD

**Issue by pdoehle** [pdoehle/parallelFinal#1]
Hi Collin,

Here is a fresh start. Running the auto-dufei-gpu from command line will run on your personal machine. Stampede script on Stampede, and I haven't had luck getting the cowboy script working. When it does I will add it. I separated it into two directories. One has binning code the other doesn't. We can work on optimizing both and see which one we like better in the end.

**Comment by collinn** [comment]
Phillip,

Dude, I'm seriously impressed. I haven't had much of a chance to look at my function (outside of what I did yesterday evening); it's been a pretty full day. It doesn't say so on this post, but from what I think I saw in your last commit comment, you have everything up and working on all three platforms? That's frat. 
Also, I wanted to add - had you had a chance to look at the serial code that Dr. Brunson sent us? I looked briefly at it this morning before work, and at first glance it looked the same to me. I'll inspect it more closely and see if it adds any advantage to our ability to parallelize it. 
Dude, seriously. Thank you for doing this. You're awesome
